CREATE OR REPLACE TABLE DEMONSTRATION.WEATHER.GLOBAL_WEATHER_REPOSITORY
COMMENT = 'Global weather observations repository'
(
    country                        VARCHAR(100)  COMMENT 'Country of the weather data',
    location_name                  VARCHAR(200)  COMMENT 'Name of the location (city)',
    latitude                       FLOAT         COMMENT 'Latitude coordinate of the location',
    longitude                      FLOAT         COMMENT 'Longitude coordinate of the location',
    timezone                       VARCHAR(100)  COMMENT 'Timezone of the location',
    last_updated_epoch             BIGINT        COMMENT 'Unix timestamp of the last data update',
    last_updated                   TIMESTAMP_NTZ COMMENT 'Local time of the last data update',
    temperature_celsius            FLOAT         COMMENT 'Temperature in degrees Celsius',
    temperature_fahrenheit         FLOAT         COMMENT 'Temperature in degrees Fahrenheit',
    condition_text                 VARCHAR(100)  COMMENT 'Weather condition description',
    wind_mph                       FLOAT         COMMENT 'Wind speed in miles per hour',
    wind_kph                       FLOAT         COMMENT 'Wind speed in kilometers per hour',
    wind_degree                    INT           COMMENT 'Wind direction in degrees',
    wind_direction                 VARCHAR(10)   COMMENT 'Wind direction as a 16-point compass',
    pressure_mb                    FLOAT         COMMENT 'Pressure in millibars',
    pressure_in                    FLOAT         COMMENT 'Pressure in inches',
    precip_mm                      FLOAT         COMMENT 'Precipitation amount in millimeters',
    precip_in                      FLOAT         COMMENT 'Precipitation amount in inches',
    humidity                       INT           COMMENT 'Humidity as a percentage',
    cloud                          INT           COMMENT 'Cloud cover as a percentage',
    feels_like_celsius             FLOAT         COMMENT 'Feels-like temperature in Celsius',
    feels_like_fahrenheit          FLOAT         COMMENT 'Feels-like temperature in Fahrenheit',
    visibility_km                  FLOAT         COMMENT 'Visibility in kilometers',
    visibility_miles               FLOAT         COMMENT 'Visibility in miles',
    uv_index                       FLOAT         COMMENT 'UV Index',
    gust_mph                       FLOAT         COMMENT 'Wind gust in miles per hour',
    gust_kph                       FLOAT         COMMENT 'Wind gust in kilometers per hour',
    air_quality_Carbon_Monoxide    FLOAT         COMMENT 'Air quality measurement: Carbon Monoxide',
    air_quality_Ozone              FLOAT         COMMENT 'Air quality measurement: Ozone',
    air_quality_Nitrogen_dioxide   FLOAT         COMMENT 'Air quality measurement: Nitrogen Dioxide',
    air_quality_Sulphur_dioxide    FLOAT         COMMENT 'Air quality measurement: Sulphur Dioxide',
    air_quality_PM2_5              FLOAT         COMMENT 'Air quality measurement: PM2.5',
    air_quality_PM10               FLOAT         COMMENT 'Air quality measurement: PM10',
    air_quality_us_epa_index       INT           COMMENT 'Air quality measurement: US EPA Index',
    air_quality_gb_defra_index     INT           COMMENT 'Air quality measurement: GB DEFRA Index',
    sunrise                        VARCHAR(20)   COMMENT 'Local time of sunrise',
    sunset                         VARCHAR(20)   COMMENT 'Local time of sunset',
    moonrise                       VARCHAR(20)   COMMENT 'Local time of moonrise',
    moonset                        VARCHAR(20)   COMMENT 'Local time of moonset',
    moon_phase                     VARCHAR(50)   COMMENT 'Current moon phase',
    moon_illumination              INT           COMMENT 'Moon illumination percentage'
);