COPY INTO DEMONSTRATION.WEATHER.GLOBAL_WEATHER_REPOSITORY
FROM @DEMONSTRATION.WEATHER.INGEST/GWR.csv
FILE_FORMAT = (TYPE = 'CSV'
               FIELD_DELIMITER = ','
               NULL_IF = ('','NULL')
               PARSE_HEADER = TRUE
               )

MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
ON_ERROR = 'ABORT_STATEMENT';